# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# Be strict when checking our package
warnings_are_errors: false

install:
  - Rscript -e 'install.packages(c("devtools", "roxygen2", "stringr", "knitr", "data.table", "curl"))'
  - Rscript -e 'install.packages(c("shiny", "shinyjs", "shinyFiles", "DT", "shinyBS", "future", "testit", "jsonlite", "shinyAce", "envDocument", "rhandsontable"))'
  - Rscript -e 'devtools::install_github(c("tdhock/namedCapture", "trestletech/shinyTree"))'
  - Rscript -e 'devtools::install_bioc(c("BiocInstaller", "rhdf5"))'

env:
  - TYPE=framework TEST_DIR=sources/framework/visioneval
  - TYPE=module    TEST_DIR=sources/modules/VE2001NHTS
  - TYPE=module    TEST_DIR=sources/modules/VEAltModes
  - TYPE=module    TEST_DIR=sources/modules/VELandUse
  - TYPE=module    TEST_DIR=sources/modules/VESimHouseholds
  - TYPE=module    TEST_DIR=sources/modules/VESyntheticFirms
  - TYPE=module    TEST_DIR=sources/modules/VETransportSupply
  - TYPE=module    TEST_DIR=sources/modules/VEVehicleOwnership
  - TYPE=model     TEST_DIR=sources/models/VERPAT
  - TYPE=model     TEST_DIR=sources/models/VERSPM/Test1
  - TYPE=gui       TEST_DIR=sources/VEGUI

script:
  - cd $TEST_DIR
  - if [ $TYPE = "framework" ]; then
      Rscript -e 'devtools::install_deps(".")';
      Rscript -e 'devtools::check(".")';
      Rscript tests/scripts/test.R;
    elif [ $TYPE = "module" ]; then
      R CMD INSTALL sources/framework/visioneval;
      Rscript -e 'devtools::install_deps(".")';
      Rscript -e 'devtools::check(".")';
      Rscript tests/scripts/test.R;
    elif [ $TYPE = "model" ]; then
      R CMD INSTALL sources/framework/visioneval;
      R CMD INSTALL sources/modules/VE2001NHTS;
      R CMD INSTALL sources/modules/VEAltModes;
      R CMD INSTALL sources/modules/VELandUse;
      R CMD INSTALL sources/modules/VESimHouseholds;
      R CMD INSTALL sources/modules/VESyntheticFirms;
      R CMD INSTALL sources/modules/VETransportSupply;
      R CMD INSTALL sources/modules/VEVehicleOwnership;
      Rscript run_model.R;
    elif [ $TYPE = "gui" ]; then
      R CMD INSTALL sources/framework/visioneval;
      R CMD INSTALL sources/modules/VE2001NHTS;
      R CMD INSTALL sources/modules/VEAltModes;
      R CMD INSTALL sources/modules/VELandUse;
      R CMD INSTALL sources/modules/VESimHouseholds;
      R CMD INSTALL sources/modules/VESyntheticFirms;
      R CMD INSTALL sources/modules/VETransportSupply;
      R CMD INSTALL sources/modules/VEVehicleOwnership;
      #need to navigate to VERPAT and run;
      #need to navigate to VERSPM and run;
      Rscript -e 'library("shiny"); runApp("app.R")';
    fi