# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# Be strict when checking our package
warnings_are_errors: false

install:
  - Rscript -e 'install.packages(c("devtools", "roxygen2", "stringr", "knitr"))'
  - Rscript -e 'devtools::install_bioc(c("BiocInstaller", "rhdf5"))'

env:
  - TYPE=framework TEST_DIR=sources/framework/visioneval
  - TYPE=module    TEST_DIR=sources/modules/VEAltModes
  - TYPE=module    TEST_DIR=sources/modules/VELandUse
  - TYPE=module    TEST_DIR=sources/modules/VESimHouseholds
  - TYPE=module    TEST_DIR=sources/modules/VESyntheticFirms
  - TYPE=module    TEST_DIR=sources/modules/VETransportSupply
  - TYPE=module    TEST_DIR=sources/modules/VEVehicleOwnership
  - TYPE=model     TEST_DIR=sources/models/VERPAT
  - TYPE=model     TEST_DIR=sources/models/VERSPM/test1
  - TYPE=gui       TEST_DIR=sources/VEGUI

script:
  - echo TYPE $TYPE TEST_DIR $TEST_DIR
  - cd $TEST_DIR
  - test $TYPE = "framework" && Rscript -e 'devtools::install_deps(".")' && Rscript -e 'devtools::check(".")'
  - test $TYPE = "module"    && Rscript -e 'devtools::install_deps(".")' && Rscript -e 'devtools::check(".")' && Rscript tests/scripts/test.R
  - test $TYPE = "model"     && Rscript run_model.R
  - test $TYPE = "gui"       && Rscript -e 'library("shiny"); runApp("app.R")'