# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
dist: trusty
cache: packages
  
# Be strict when checking our package
warnings_are_errors: false

# nloptr R package requires libnlopt-dev to be installed, which requires trusty ubuntu
# phantomjs required for shinytest for VEGUI testing
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libnlopt-dev
  - "export PHANTOMJS_VERSION=2.1.1"
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "hash -r"
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then hash -r; fi"
  - "phantomjs --version"

# fast binary package install
r_binary_packages: 
  - curl
  - devtools
  - roxygen2
  - stringr
  - knitr
  - data.table
  - ordinal
  - geosphere
  - fields
  - car
  - pbkrtest
  - quantreg
  - reshape
  - pbkrtest
  - shiny
  - shinyjs
  - shinyFiles
  - DT
  - shinyBS
  - future
  - testit
  - jsonlite
  - shinyAce
  - envDocument
  - rhandsontable
  
bioc_packages:
  - BiocInstaller
  - rhdf5

r_github_packages:
  - tdhock/namedCapture
  - trestletech/shinyTree
  - rstudio/webdriver
  - rstudio/shinytest

# setup a different environment variable for each Travis build environment (in the matrix) to run in parallel
env:
   - FOLDER=sources/framework/visioneval         SCRIPT='tests/scripts/test.R'    PACKAGE=true
   - FOLDER=sources/modules/VE2001NHTS           SCRIPT='tests/scripts/test.R'    PACKAGE=true
   - FOLDER=sources/modules/VESimHouseholds      SCRIPT='tests/scripts/test.R'    PACKAGE=true
   - FOLDER=sources/modules/VELandUse            SCRIPT='tests/scripts/test.R'    PACKAGE=true
   - FOLDER=sources/modules/VESyntheticFirms     SCRIPT='tests/scripts/test.R'    PACKAGE=true
   - FOLDER=sources/modules/VETransportSupply    SCRIPT='tests/scripts/test.R'    PACKAGE=true
   - FOLDER=sources/modules/VECommercialTravel   SCRIPT='tests/scripts/test.R'    PACKAGE=true
   - FOLDER=sources/modules/VEHouseholdTravel    SCRIPT='tests/scripts/test.R'    PACKAGE=true
   - FOLDER=sources/modules/VEHouseholdVehicles  SCRIPT='tests/scripts/test.R'    PACKAGE=true
   - FOLDER=sources/models/VERPAT                SCRIPT='run_model.R'             PACKAGE=false
   - FOLDER=sources/models/VERSPM/Test1          SCRIPT='run_model.R'             PACKAGE=false
   - FOLDER=sources/VEGUI                        SCRIPT='run_vegui_test.R'        PACKAGE=false

# install and test framework, modules, models, GUI
script:
  - |
    cd $FOLDER
    if [ $PACKAGE == "true" ]; then
      Rscript -e 'devtools::install_deps(".")'
      Rscript -e 'devtools::check(".")'
    fi
    Rscript -e "tryCatch( source( $SCRIPT ) )"
    if [ $PACKAGE == "true" ]; then
      R CMD INSTALL .
    fi
 