# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# Be strict when checking our package
warnings_are_errors: false

# Specify folder
install:
  - Rscript -e 'install.packages(c("devtools", "roxygen2", "stringr"))'
  - Rscript -e 'devtools::install_bioc(c("BiocInstaller", "rhdf5"))'
env:
  - TEST_DIR=sources/framework/visioneval
  - TEST_DIR=sources/modules/VETransportSupply
script:
  - cd $TEST_DIR
  - Rscript -e 'devtools::install_deps(".")'
  - Rscript -e 'devtools::check(".")'
