# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# Be strict when checking our package
warnings_are_errors: false

# Specify folder
install:
  - Rscript -e 'install.packages(c("devtools", "roxygen2"))'
script:
  - cd sources/framework
  - Rscript -e 'devtools::install_deps("visioneval")'
  - Rscript -e 'devtools::check("visioneval")'
